#version: '3.4'

services:

  pgadmin:
    image: dpage/pgadmin4

  card.api:
    image: ${DOCKER_REGISTRY-}cardapi
    build:
      context: .
      dockerfile: Card.API/Dockerfile
  
  portainer:
    image: portainer/portainer-ce
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: Ocelot.ApiGateway/Dockerfile

volumes:
 portainer_data:
 postgres_data:
 pgadmin_data:
 elasticsearch-data:



